from django.urls import path
from . import views

urlpatterns = [
    path('', views.index ),
    path('one', views.one),
    path('two', views.two),
    path('threee', views.threee),
    path('four', views.four),
    path('fiveone', views.fiveone),
    path('fivetwo', views.fivetwo),
    path('fivethree', views.fivethree),
    path('fivefour', views.fivefour),
    path('fivefive', views.fivefive),
    path('fivesix', views.fivesix),
    path('fiveseven', views.fiveseven),
    path('fiveeight', views.fiveeight),
    path('sixone', views.sixone),
    path('sixtwo', views.sixtwo),
    path('sixthree', views.sixthree),
    path('sixfour', views.sixfour),
    path('sevenone', views.sevenone),
    path('seventwo', views.seventwo),
    path('seventhree', views.seventhree),
    path('sevenfive', views.sevenfive),
    path('note', views.note),
    path('final', views.final),
    path('aone', views.aone),
    path('atwo', views.atwo),
    path('athree', views.athree),
    path('afour', views.afour),
    path('asix', views.asix),
    path('afive', views.afive),
    path('aseven', views.aseven),
    path('aeight', views.aeight),
    path('anine', views.anine),
    path('aten', views.aten),
    path('bone', views.bone),
    path('btwo', views.btwo),
    path('bthree', views.bthree),
    path('bfour', views.bfour),
    path('bfive', views.bfive),
    path('bfinal', views.final),
]
